// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthRegisterResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterInput struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	AuthPassword string `json:"authPassword"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}
